# Generated by Django 4.2.13 on 2024-05-18 04:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0003_delete_customuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('gender', models.CharField()),
                ('dateNum', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tip', models.TextField()),
                ('dateIdeas', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dates', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Dates',
        ),
    ]
