# Generated by Django 4.2.13 on 2024-06-04 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_date_delete_dates'),
    ]

    operations = [
        migrations.RenameField(
            model_name='date',
            old_name='dateNum',
            new_name='dateCount',
        ),
    ]
