# Generated by Django 4.2.13 on 2024-06-05 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_datenum_date_datecount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date',
            name='fname',
            field=models.CharField(),
        ),
    ]
